version: '3.8'

services:

    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: amoCMS
            MYSQL_USER: dba
            MYSQL_PASSWORD: "passw"
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
